apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - image: "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
        env:
          - name: GITHUB_REPO
            value: "$GITHUB_REPO"
          - name: GITHUB_TOKEN
            value: "$GITHUB_TOKEN"
        name: ""
