apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - image: "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
        env:
          - name: GITHUB_REPO
            value: "$GITHUB_REPO"
          - name: GITHUB_TOKEN
            value: "$GITHUB_TOKEN"
